[package]
name = "gadd"
version = "0.1.0"
edition = "2021"
authors = ["hermannm"]
license = "MIT"
description = "Command-line utility for staging changes to Git (alternative to git-add's interactive mode)."
keywords = ["git"]
categories = ["command-line-utilities"]
repository = "https://github.com/hermannm/gadd"

[dependencies]
anyhow = "1.0.70"
crossterm = "0.26.1"
git2 = "0.17.1"
openssl-sys = { version = "*", features = ["vendored"] }
ratatui = "0.20.1"
