[package]
name = "gadd"
version = "0.2.0"
edition = "2021"
authors = ["hermannm"]
license = "MIT"
description = "Command-line utility for staging changes to Git (alternative to git-add's interactive mode)."
keywords = ["git"]
categories = ["command-line-utilities"]
repository = "https://github.com/hermannm/gadd"
exclude = ["cross-compile.sh"]

[dependencies]
anyhow = "1.0.70"
crossterm = "0.26.1"
git2 = { version = "0.17.1", default-features = false }
ratatui = "0.20.1"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.3.9"
